---
- name: Update Root Password
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    new_root_password: "1223qwwe"
    # Set the password exp date (in days) from the last password change
    password_expiry_days: 61

  tasks:
  - name: Update root password
    user:
      name: root
      password: "{{ new_root_password | password_hash('sha512') }}"
      expires: -1  # Make sure the password doesn't expire immediately

  - name: Set password expiry to 61 days from now
    command: chage -M "{{ password_expiry_days }}" root
    # -M sets the max number of days the password is valid
    # This will make the password expire 61 days after the password is last updated
